### ISSUE TITLE
Not nullable body on success

### ISSUE THREAD

**Issue by jakoss** [skydoves/Sandwich#20]
In `ApiResponse.Success` the `data` property is nullable. And i understand why it is - it's just a wrapper around retrofit response logic. But, when i'm using clean `suspend fun something(): Type` i will get an exception if the returned type is null. Which is good, i do expect that!

If i wanted null to be possible in my response - i would use a nullable type as a generic parameter. If i don't - my assumption is that in case of success it will always be properly created. The need for another null check does make the whole `Success` type pointless in my opinion. Because i'm still not sure if it really was a success, i have to do another check..

Have you considered handling that?

**Comment by skydoves** [comment]
Hi, @jakoss 
Your issue is very worth agenda to discuss in this API interface.
The `data` property in the `ApiResponse.Success` will be null if the response has been succeeded, but the body data is empty (e.g., 204-No Content). So I designed following the `Retrofit`'s interfaces at the beginning. 

So I was thought of implementing another expression for handling the empty body response like `onComplete` and changing the type of the data to non-nullable. But it was a little questionable whether it is efficient to create a new expression for handling empty body responses in another way because we can handle both cases in the `onSuccess` expression.

If you have an idea for handling the empty body cases, I hope to get any feedback for supporting better interfaces! :)

**Comment by jakoss** [comment]
From my perspective `204` should be always by design. So when i want to handle 204 i just don't require any response type (in Sandwich that could be represented by a `Unit` type maybe? (I'm not 100% sure about that, but maybe Sandwich could allow 204 as a success only if return type is `Unit`? Is that even possible in kotlin, not sure here :) ).

Or maybe different response handling type, something like `NoContentApiResponse` instead of `ApiResponse`. That seems to me like fine explicit solution to that. That way programmer always have to explicitly declare that they do not expect body.

**Comment by skydoves** [comment]
You're right. :) And moreover, we don't require to handle the data when the `204` response case, which means also we don't need to check the nullability. (For the `204` response case, we don't need to access the data property at all).

I'm considering changing the type of the data property to non-null, and It will throw `NoContentException` when trying to access the body is null. Also, I'm considering implementing `onComplete scope function to handle which has no response receivers for processing only the `no-content` case.

Thanks for sharing your feedback :)

**Comment by jakoss** [comment]
Throwing on body access while in 204 seems fine. Like I said, it should always be by design anyway 😁

**Comment by skydoves** [comment]
@jakoss 
This feature has been included in the `1.2.0-SNAPSHOT` and it will be released on the next version.
Thank you for your issue! 👍

**Comment by skydoves** [comment]
Released a new stable `1.2.0`. 🎉

**Comment by hiberfake** [comment]
@skydoves what do you suggest, if the API endpoint returns "200" with a body, but can also return "204"?  Is a good approach to catch the `NoContentException` in this case?
